services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data-8.0:/data/db # Persist MongoDB data
      - mongo-config-8.0:/data/configdb # Persist MongoDB configuration

volumes:
  mongo-data-8.0:
    driver: local
  mongo-config-8.0:
    driver: local